In [2]:
from gensim.models.word2vec import KeyedVectors

In [3]:
data = KeyedVectors.load_word2vec_format("./Data/Tencent_AILab_ChineseEmbedding.txt",binary=False,limit=50000)

In [5]:
data["他"]

array([ 3.56082e-01, -1.80596e-01,  1.85805e-01,  7.63270e-02,
        3.31199e-01, -9.50900e-02,  8.37840e-02,  1.63685e-01,
        3.94450e-02,  1.65298e-01, -2.10911e-01, -1.44029e-01,
        2.62070e-02, -8.11700e-03,  1.15159e-01,  1.53219e-01,
       -3.15223e-01, -3.15678e-01, -1.25675e-01, -2.75004e-01,
        4.86270e-02, -2.61640e-02, -2.07428e-01,  1.38856e-01,
        1.60630e-02,  2.96121e-01, -1.52143e-01,  8.59530e-02,
        3.65987e-01, -1.81412e-01, -1.95845e-01, -2.74850e-02,
       -1.44713e-01,  1.66965e-01, -2.08822e-01, -2.05306e-01,
        1.87133e-01,  6.97100e-02, -1.64495e-01,  1.91943e-01,
        4.93540e-02, -2.05522e-01,  4.01674e-01, -1.09109e-01,
       -2.89946e-01,  1.74193e-01, -4.44713e-01, -5.79710e-01,
       -6.91250e-02, -7.07270e-02, -2.84029e-01,  1.02862e-01,
       -2.59838e-01,  1.23419e-01,  2.41752e-01,  4.69550e-02,
        3.35250e-02,  6.42000e-02,  3.90926e-01,  3.18953e-01,
        1.20240e-02,  1.13651e-01,  2.23803e-01, -2.410

In [4]:
import numpy as np
import pandas as pd

In [2]:
tmp = np.arange(200)

In [3]:
np.random.choice(tmp.shape)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [5]:
data = pd.read_excel("./Data/文本分词.xlsx")

In [9]:
random_sample = np.random.choice(data.shape[0],2000)

In [16]:
from sklearn import preprocessing

In [14]:
data.iloc[random_sample,:]

Unnamed: 0   分类                                                 正文  \
6055        6055   体育  【 文献号 】3-1463\n【原文出处】华南师范大学学报：社科版\n【原刊地名】广州\n...   
3408        3408  计算机  软件学报\nJOURNAL OF SOFTWARE\n1999年 第1期 No.1 199...   
725          725   艺术   蒙古举办中国电影日\n新华社乌兰巴托５月２８日电（记者孙承平）为庆祝\n中蒙友好互助条约...   
8035        8035   经济  【 文献号 】1-1502\n【原文出处】社会科学\n【原刊地名】沪\n【原刊期号】199...   
5924        5924   体育  【 文献号 】2-4165\n【原文出处】体育科学\n【原刊地名】京\n【原刊期号】199...   
...          ...  ...                                                ...   
7868        7868   经济  【 文献号 】1-1649\n【原文出处】社会科学\n【原刊地名】沪\n【原刊期号】199...   
6562        6562   体育  【 文献号 】2-2800\n【原文出处】光明日报\n【原刊地名】京\n【原刊期号】199...   
4767        4767   农业  【 文献号 】1-3074\n【原文出处】华中理工大学学报：社科版\n【原刊地名】武汉\n...   
9244        9244   法律  ２１５\n 企业 管理 体制 与 生产 经营   \n０６０１\n１９８７ 年 ３月 ２４...   
915          915   历史  【 文献号 】1-3742\n【原文出处】山西大学学报：哲社版\n【原刊地名】武汉\n【原...   

                                                   文本分词  
6055   【   文献号   】 3 - 1463 \n 【 原文 出处 】 华南 师范大学 学报...  
3408   软件 学报 \n JOURNAL   OF   SOFTWARE \n 1999 年  ...  
725      蒙古 举办 中国 电影 日 \n 新华社 乌兰巴托 ５ 月 ２ ８ 日电 （ 记者 ...  
8035   【   文献号   】 1 - 1502 \n 【 原文 出处 】 社会科学 \n 【 ...  
5924   【   文献号   】 2 - 4165 \n 【 原文 出处 】 体育 科学 \n 【...  
...                                                 ...  
7868   【   文献号   】 1 - 1649 \n 【 原文 出处 】 社会科学 \n 【 ...  
6562   【   文献号   】 2 - 2800 \n 【 原文 出处 】 光明日报 \n 【 ...  
4767   【   文献号   】 1 - 3074 \n 【 原文 出处 】 华中理工大学 学报 ...  
9244   ２ １ ５ \n   企业   管理   体制   与   生产   经营       ...  
915    【   文献号   】 1 - 3742 \n 【 原文 出处 】 山西大学 学报 ： ...  

[2000 rows x 4 columns]

In [17]:
lbl_enc = preprocessing.LabelEncoder()
y = lbl_enc.fit_transform(data.分类.values)

In [18]:
y

array([16, 16, 16, ...,  9,  9,  9])

In [24]:
tmp = np.array([[0,1,2,3],[2,3,1,4],[1,0,0,0]])
predicted = np.argmax(tmp,axis=1)
actual = np.array([2,4,0])

In [25]:
np.sum(actual==predicted)/actual.shape[0]

0.3333333333333333

In [1]:
import re
import pandas as pd 
import numpy as np
import jieba

In [51]:
speech = open("E:\VINS Project\Data\speech.txt","r",encoding="utf-8")
articles = extract_article(speech)
training_data = pd.DataFrame({"articles":articles})

In [5]:
def extract_article(file):
    '''

    :param file:
    :return: 所有文章
    '''
    lines = file.readlines()
    articles = set()
    for line in lines:
        if "'article'" in line:
            line = re.findall(r'\'article\':\s\'(.*)\'\,', line)
            if len(line) > 0:
                if line[0] != '':
                    articles.add(line[0])

    return list(articles)


In [54]:
training_data["cutted_articles"] = training_data["articles"].apply(lambda i:jieba.cut(i))
training_data["cutted_articles"] = [' '.join(i) for i in training_data["cutted_articles"]]

In [56]:
training_data.to_csv("./Data/political_speech.csv")

In [55]:
training_data["cutted_articles"]

0        2016 “ 中 美 旅游 年 ” 2 月 29 日 在京开幕 。 国家 主席 习近平 向 ...
1        习近平 给 北京大学 学生 回信 勉励 当代 青年 勇 做 走 在 时代 前面 的 奋进 者...
2        3 月 13 日 ， 中国人民政治协商会议 第十三届 全国 委员会 第二次 会议 在 北京 ...
3        十三 、 坚定不移 全面 从严治党 ， 不断 提高 党 的 执政 能力 和 领导 水平 中国...
4        第十三次 上海 合作 组织 成员国 最高法院 院长 会议 25 日 在 北京 举行 。 国家...
                               ...                        
11243    国家 主席 习近平 19 日 在 人民大会堂 接受 8 国 新任 驻华大使 递交国书 。 他...
11244    习近平 对 党和国家 功勋 荣誉 表彰 工作 作出 重要 指示 强调 发挥 功勋 荣誉 精神...
11245    22 日 下午 ， 正在 福建 武夷山市 考察 的 习近平 总书记 来到 朱熹 园 ， 了解...
11246    七月 十六日 晚 ， 国家 主席 习近平 应邀 在 北京 以 视频 方式 出席 亚太经合组织...
11247    5 月 28 日 ， 国家 主席 习近平 在 北京人民大会堂 会见 瓦努阿图 总理 萨尔 维...
Name: cutted_articles, Length: 11248, dtype: object

In [40]:
tmp = training_data.iloc[0,:]["articles"]
tmp

'2016“中美旅游年”2月29日在京开幕。国家主席习近平向开幕式致贺词。习近平指出，共同举办2016“中美旅游年”是我去年9月对美国进行国事访问期间双方达成的一项重要成果。值此2016“中美旅游年”开幕之际，我谨代表中国政府和人民，并以我个人的名义，对旅游年的开幕表示热烈的祝贺，对远道而来的美国朋友表示热烈的欢迎。习近平指出，中美建交37年来，两国关系取得历史性发展。近年来，双方共同努力推进中美新型大国关系建设，两国在诸多重要领域、重大国际和地区问题上开展了富有成效的协调与合作，不仅造福两国和两国人民，而且有力促进了世界和平、稳定、繁荣。习近平表示，中美都有灿烂的文化、优美的风光，两国人民都有加深了解、增进友谊的强烈愿望。希望双方以举办旅游年为契机，扩大人员往来，加强文化交流，为中美关系发展培育更为厚实的民意和社会基础。欢迎更多美国朋友来中国旅游。祝2016“中美旅游年”圆满成功。(新华社北京3月1日电)'

In [44]:
tmp_cutted = jieba.cut(tmp)
tmp2 = ['*'.join(i) for i in tmp_cutted]

In [50]:
text = "我时习近平"
text_cutted = jieba.cut(text)
[]

我时
习近平


t

In [28]:
training_data = pd.read_csv("./Data/political_speech.csv")

NameError: name 'pd' is not defined

In [3]:
training_data.head()

Unnamed: 0                                           articles  \
0           0  2016“中美旅游年”2月29日在京开幕。国家主席习近平向开幕式致贺词。习近平指出，共同举办...   
1           1  习近平给北京大学学生回信勉励当代青年勇做走在时代前面的奋进者开拓者奉献者五四青年节即将到来之...   
2           2  3月13日，中国人民政治协商会议第十三届全国委员会第二次会议在北京闭幕。这是习近平、李克强、...   
3           3  十三、坚定不移全面从严治党，不断提高党的执政能力和领导水平中国特色社会主义进入新时代，我们党...   
4           4  第十三次上海合作组织成员国最高法院院长会议25日在北京举行。国家主席习近平致贺信，对会议召开...   

                                     cutted_articles  
0  2016 “ 中 美 旅游 年 ” 2 月 29 日 在京开幕 。 国家 主席 习近平 向 ...  
1  习近平 给 北京大学 学生 回信 勉励 当代 青年 勇 做 走 在 时代 前面 的 奋进 者...  
2  3 月 13 日 ， 中国人民政治协商会议 第十三届 全国 委员会 第二次 会议 在 北京 ...  
3  十三 、 坚定不移 全面 从严治党 ， 不断 提高 党 的 执政 能力 和 领导 水平 中国...  
4  第十三次 上海 合作 组织 成员国 最高法院 院长 会议 25 日 在 北京 举行 。 国家...

In [4]:
import joblib

In [6]:
tokenizer = joblib.load("./Data/Pretrained_Tokenizer/Tokenizer.pkl")

In [20]:
article_2 = tokenizer.texts_to_sequences(training_data.iloc[2,:]["articles"])

In [16]:
seq = sequence.pad_sequences(article_2,maxlen=50)

In [13]:
from keras.preprocessing import text,sequence

In [18]:
seq.shape

(2761, 50)

In [28]:
art= tokenizer.texts_to_sequences([training_data.iloc[2,:]["cutted_articles"]])

In [37]:
tt = sequence.pad_sequences(art,maxlen=50)

In [36]:
t = "a"
type(t)==str

True

In [38]:
type(tt)

numpy.ndarray

In [27]:
training_data.iloc[2,:]["articles"]

NameError: name 'training_data' is not defined

In [40]:
gen = jieba.cut("世界级国家博物馆")

In [41]:
[i for i in gen]

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\Public\Documents\Wondershare\CreatorTemp\jieba.cache
Loading model cost 0.608 seconds.
Prefix dict has been built successfully.


['世界级', '国家博物馆']

In [42]:
import gensim
from gensim.models.word2vec import KeyedVectors

C:\Users\DELL\anaconda3\lib\site-packages\gensim\similarities\__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)


In [2]:
from core.utils.text_preprocessing import TextPreprocessing

In [30]:
textCutter = TextPreprocessing(training_embedding=False,training_tf_idf=False,use_tf_idf=True)

获取train_data中
加载已有数据
获取train_tokenizer中
加载预训练Tokenizer
获取embedding_matrix中
加载预训练Embedding Matrix


In [10]:
tmp = textCutter.tokenize_for_text(maxlen=100)

In [19]:
import numpy as np
np.random.rand(1,20)

array([[0.85342181, 0.81054257, 0.47653628, 0.8853717 , 0.47966588,
        0.18083302, 0.43607915, 0.71691961, 0.99739437, 0.05864728,
        0.55822592, 0.62561374, 0.506411  , 0.91931289, 0.48731491,
        0.31903991, 0.8961653 , 0.08288073, 0.22631831, 0.64736649]])

In [22]:
a = np.sqrt(6/1+200)

t1 = np.random.rand(1,2)

In [23]:
t2 = np.random.rand(1,2)

In [44]:
textCutter.training_data

Unnamed: 0                                           articles  \
0               0  2016“中美旅游年”2月29日在京开幕。国家主席习近平向开幕式致贺词。习近平指出，共同举办...   
1               1  习近平给北京大学学生回信勉励当代青年勇做走在时代前面的奋进者开拓者奉献者五四青年节即将到来之...   
2               2  3月13日，中国人民政治协商会议第十三届全国委员会第二次会议在北京闭幕。这是习近平、李克强、...   
3               3  十三、坚定不移全面从严治党，不断提高党的执政能力和领导水平中国特色社会主义进入新时代，我们党...   
4               4  第十三次上海合作组织成员国最高法院院长会议25日在北京举行。国家主席习近平致贺信，对会议召开...   
...           ...                                                ...   
11243       11243  国家主席习近平19日在人民大会堂接受8国新任驻华大使递交国书。他们是：斐济驻华大使纳伊瓦卢鲁...   
11244       11244  习近平对党和国家功勋荣誉表彰工作作出重要指示强调发挥功勋荣誉精神引领典型示范作用推动全社会见...   
11245       11245  22日下午，正在福建武夷山市考察的习近平总书记来到朱熹园，了解朱熹生平及理学研究等情况。习近...   
11246       11246  七月十六日晚，国家主席习近平应邀在北京以视频方式出席亚太经合组织领导人非正式会议并发表讲话。...   
11247       11247  5月28日，国家主席习近平在北京人民大会堂会见瓦努阿图总理萨尔维。新华社记者黄敬文摄本报北京...   

                                         cutted_articles  
0      2016 “ 中 美 旅游 年 ” 2 月 29 日 在京开幕 。 国家 主席 习近平 向 ...  
1      习近平 给 北京大学 学生 回信 勉励 当代 青年 勇 做 走 在 时代 前面 的 奋进 者...  
2      3 月 13 日 ， 中国人民政治协商会议 第十三届 全国 委员会 第二次 会议 在 北京 ...  
3      十三 、 坚定不移 全面 从严治党 ， 不断 提高 党 的 执政 能力 和 领导 水平 中国...  
4      第十三次 上海 合作 组织 成员国 最高法院 院长 会议 25 日 在 北京 举行 。 国家...  
...                                                  ...  
11243  国家 主席 习近平 19 日 在 人民大会堂 接受 8 国 新任 驻华大使 递交国书 。 他...  
11244  习近平 对 党和国家 功勋 荣誉 表彰 工作 作出 重要 指示 强调 发挥 功勋 荣誉 精神...  
11245  22 日 下午 ， 正在 福建 武夷山市 考察 的 习近平 总书记 来到 朱熹 园 ， 了解...  
11246  七月 十六日 晚 ， 国家 主席 习近平 应邀 在 北京 以 视频 方式 出席 亚太经合组织...  
11247  5 月 28 日 ， 国家 主席 习近平 在 北京人民大会堂 会见 瓦努阿图 总理 萨尔 维...  

[11248 rows x 3 columns]

In [25]:
t2

array([[0.14697613, 0.8257323 ]])

In [26]:
t1+t2

array([[0.1478604, 1.503224 ]])

In [32]:
dataset = list(textCutter.training_data["cutted_articles"])

In [33]:
dataset = [i.split(" ") for i in dataset]

In [41]:
from snownlp import SnowNLP

In [51]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [49]:
s = SnowNLP([dataset[1]])

In [105]:
training_data = textCutter.training_data

In [94]:
joined = ' '.join(dataset[0])

In [95]:
joined

'2016 “ 中 美 旅游 年 ” 2 月 29 日 在京开幕 。 国家 主席 习近平 向 开幕式 致 贺词 。 习近平 指出 ， 共同 举办 2016 “ 中 美 旅游 年 ” 是 我 去年 9 月 对 美国 进行 国事访问 期间 双方 达成 的 一项 重要 成果 。 值此 2016 “ 中 美 旅游 年 ” 开幕 之际 ， 我谨 代表 中国政府 和 人民 ， 并 以 我 个人 的 名义 ， 对 旅游 年 的 开幕 表示 热烈 的 祝贺 ， 对 远道而来 的 美国 朋友 表示 热烈 的 欢迎 。 习近平 指出 ， 中 美 建交 37 年来 ， 两国关系 取得 历史性 发展 。 近年来 ， 双方 共同努力 推进 中 美 新型 大国 关系 建设 ， 两国 在 诸多 重要 领域 、 重大 国际 和 地区 问题 上 开展 了 富有成效 的 协调 与 合作 ， 不仅 造福 两国 和 两国人民 ， 而且 有力 促进 了 世界 和平 、 稳定 、 繁荣 。 习近平 表示 ， 中美 都 有 灿烂 的 文化 、 优美 的 风光 ， 两国人民 都 有 加深了解 、 增进友谊 的 强烈 愿望 。 希望 双方 以 举办 旅游 年 为 契机 ， 扩大 人员 往来 ， 加强 文化交流 ， 为 中美关系 发展 培育 更为 厚实 的 民意 和 社会 基础 。 欢迎 更 多 美国 朋友 来 中国 旅游 。 祝 2016 “ 中 美 旅游 年 ” 圆满成功 。 ( 新华社 北京 3 月 1 日电 )'

In [111]:
tmp1 = training_data["articles"][0]

In [113]:
import jieba

In [116]:
import pandas as pd
df = pd.DataFrame([tmp1],columns=["cutted"])

In [117]:
df

cutted
0  2016“中美旅游年”2月29日在京开幕。国家主席习近平向开幕式致贺词。习近平指出，共同举办...

In [118]:
def jieba_cut(x):
    x = jieba.cut(x)
    return " ".join(x)

df["cutted"] = df["cutted"].apply(jieba_cut)

In [119]:
tmp_list1=df["cutted"][0].split(" ")

In [121]:
tmp_list2=dataset[0]

In [122]:
tmp1_list1 == tmp_list2

True

In [120]:
tmp_list1

['2016',
 '“',
 '中',
 '美',
 '旅游',
 '年',
 '”',
 '2',
 '月',
 '29',
 '日',
 '在京开幕',
 '。',
 '国家',
 '主席',
 '习近平',
 '向',
 '开幕式',
 '致',
 '贺词',
 '。',
 '习近平',
 '指出',
 '，',
 '共同',
 '举办',
 '2016',
 '“',
 '中',
 '美',
 '旅游',
 '年',
 '”',
 '是',
 '我',
 '去年',
 '9',
 '月',
 '对',
 '美国',
 '进行',
 '国事访问',
 '期间',
 '双方',
 '达成',
 '的',
 '一项',
 '重要',
 '成果',
 '。',
 '值此',
 '2016',
 '“',
 '中',
 '美',
 '旅游',
 '年',
 '”',
 '开幕',
 '之际',
 '，',
 '我谨',
 '代表',
 '中国政府',
 '和',
 '人民',
 '，',
 '并',
 '以',
 '我',
 '个人',
 '的',
 '名义',
 '，',
 '对',
 '旅游',
 '年',
 '的',
 '开幕',
 '表示',
 '热烈',
 '的',
 '祝贺',
 '，',
 '对',
 '远道而来',
 '的',
 '美国',
 '朋友',
 '表示',
 '热烈',
 '的',
 '欢迎',
 '。',
 '习近平',
 '指出',
 '，',
 '中',
 '美',
 '建交',
 '37',
 '年来',
 '，',
 '两国关系',
 '取得',
 '历史性',
 '发展',
 '。',
 '近年来',
 '，',
 '双方',
 '共同努力',
 '推进',
 '中',
 '美',
 '新型',
 '大国',
 '关系',
 '建设',
 '，',
 '两国',
 '在',
 '诸多',
 '重要',
 '领域',
 '、',
 '重大',
 '国际',
 '和',
 '地区',
 '问题',
 '上',
 '开展',
 '了',
 '富有成效',
 '的',
 '协调',
 '与',
 '合作',
 '，',
 '不仅',
 '造福',
 '两国',
 '和',
 '两国人民',
 '，',
 '而且',
 '有力',
 '